'@gympass/yoga':
  - 'packages/yoga/*'
'@gympass/yoga-doc':
  - 'packages/doc/*'
'@gympass/yoga-icons':
  - 'packages/icons/*'
'@gympass/yoga-tokens':
  - 'packages/tokens/*'
'@gympass/yoga-common':
  - 'packages/common/*'
'@gympass/yoga-labnative':
  - 'packages/labnative/*'
