name: Yoga - Gympass Design System

on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    if: startsWith(github.event.head_commit.message, 'Merge')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Configure CI Git User
        run: |
          git remote set-url origin https://${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git checkout master
          git config --global user.email octobot@github.com
          git config --global user.name GitHub Actions
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: yarn
      - name: Lint
        run: yarn lint:all
      - name: Test
        run: yarn test
      - name: Build
        run: |
          CI=true
          yarn build
      - name: Publish
        run: |
          GH_TOKEN=${GH_TOKEN}
          NPM_TOKEN=${NPM_TOKEN}
          SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ./.npmrc
          yarn lerna publish --yes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
